global:
  resolve_timeout: 5m
  
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        webhook_url: 'test-alertmanager'
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 15s
      receiver: 'matrix'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
  - name: 'matrix'
    webhook_configs:
      - url: 'http://<your-ip>:<port-on-your-instance>/alerts/<simple-name>'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']