# configuration of the HTTP server
http:
  port: <port-on-your-instance> # e.g. 12345

# configuration for the Matrix connection
matrix:
  homeserver-url: "<your-homeserver-url>" # e.g. https://matrix-client.matrix.org
  user-id: "<your-bot-user-id>" # e.g. @some-username:matrix.org
  access-token: "<your-bot-access-token>" # e.g. syt_abc... 
  room-mapping:
    <simple-name>: "<your-room-id>" # e.g. !qohfwef7qwerf:example.com
# configuration of templating features
templating:
  external-url-mapping:
    "alertmanager:9093": https://alertmanager.example.com
  computed-values:
    - values:
        color: white
    - values:
        color: orange
      when-matching-labels:
        severity: warning
    - values:
        color: red
      when-matching-labels:
        severity: critical
    - values:
        color: limegreen
      when-matching-status: resolved
  firing-template: '
    <p>
      <strong><font color="{{ .ComputedValues.color }}">{{ .Alert.Status | ToUpper }}</font></strong>
      {{ if .Alert.Labels.name }}
        {{ .Alert.Labels.name }}
      {{ else if .Alert.Labels.alertname }}
        {{ .Alert.Labels.alertname }}
      {{ end }}
      >>
      {{ if .Alert.Labels.severity }}
        {{ .Alert.Labels.severity | ToUpper }}:
      {{ end }}
      {{ if .Alert.Annotations.description }}
        {{ .Alert.Annotations.description }}
      {{ else if .Alert.Annotations.summary }}
        {{ .Alert.Annotations.summary }}
      {{ end }}
      >>
      {{ if .Alert.Annotations.runbook }}
        <a href="{{ .Alert.Annotations.runbook }}">Runbook</a> |
      {{ end }}
      {{ if .Alert.Annotations.dashboard }}
        <a href="{{ .Alert.Annotations.dashboard }}">Dashboard</a> |
      {{ end }}
      <a href="{{ .SilenceURL }}">Silence</a>
    </p>'